#version 450
layout(row_major) uniform;
layout(row_major) buffer;

#line 4 0
struct MMulParams_std140_0
{
    uint M_0;
    uint K_0;
    uint N_0;
};

#line 17
layout(binding = 3)
layout(std140) uniform block_MMulParams_std140_0
{
    uint M_0;
    uint K_0;
    uint N_0;
} params_0;

#line 8
layout(std430, binding = 0) readonly buffer StructuredBuffer_float_t_0 {
    float _data[];
} A_0;
layout(std430, binding = 1) readonly buffer StructuredBuffer_float_t_1 {
    float _data[];
} B_0;
layout(std430, binding = 2) buffer StructuredBuffer_float_t_2 {
    float _data[];
} C_0;

#line 21
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main()
{

    #line 22
    uint idx_0 = gl_GlobalInvocationID.x;
    uint idy_0 = gl_GlobalInvocationID.y;

    #line 23
    bool _S1;

    if (idx_0 < (params_0.M_0))
    {

        #line 25
        _S1 = idy_0 < (params_0.N_0);

        #line 25
    }
    else
    {

        #line 25
        _S1 = false;

        #line 25
    }

    #line 25
    if (_S1)
    {

        #line 25
        uint k_0 = 0U;

        #line 25
        float sum_0 = 0.0;

        for (; ; )
        {

            #line 27
            if (k_0 < (params_0.K_0))
            {}
            else
            {

                #line 27
                break;
            }

            #line 28
            float sum_1 = sum_0 + A_0._data[uint(idx_0 * params_0.K_0 + k_0)] * B_0._data[uint(k_0 * params_0.N_0 + idy_0)];

            #line 27
            k_0 = k_0 + 1U;

            #line 27
            sum_0 = sum_1;

            #line 27
        }

        C_0._data[uint(idx_0 * params_0.N_0 + idy_0)] = sum_0;

        #line 25
    }

    #line 32
    return;
}
